language:
  - php

php:
  - 5.6

install:
  - sudo apt-get -qq install libcap-dev libcap-ng-dev

env:
  global:
   - secure: "pIwolzC0BBt15LmwOULzFrLvBURUs7fiL/lFQZSnFaOkWNAYwLbrPjmtWQjc3yyUOSURXfVQcFgPO74s3zEciWExl02QWXSsxTcQZhdmuR/Ulssk21wjWlO8zeCaAgb1fwebVjpkSf+UhUZ3dx2UNFO3RM5xJXb6TQTLRHfDPAA="

addons:
  coverity_scan:
    project:
      name: "sjinks/php-chuid"
      description: "php-chuid"
    notification_email: volodymyr@wildwolf.name
    build_command_prepend: "phpize && ./configure --with-cap --silent"
    build_command: "make --silent"
    branch_pattern: coverity

script:
  - phpize && ./configure $CAP $CAPNG --silent && make --silent
  - sudo sh -c "NO_INTERACTION=1 make test"
