language:
  - php
  - c

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

compiler:
  - gcc
  - clang

install:
  - sudo apt-get -qq install libcap-dev

script:
  - phpize && ./configure --with-cap --silent && make --silent
