language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install debhelper php5-dev libcap-dev

script:
  - phpize
  - ./configure
  - make

notifications:
  email: false
