language:
  - php
  - c

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

compiler:
  - gcc
  - clang

install:
  - sudo apt-get -qq install libcap-dev libcap-ng-dev

env:
  matrix:
    - CAP="--with-cap" CAPNG="--without-capng"
    - CAP="--without-cap" CAPNG="--with-capng"

script:
  - phpize && ./configure $CAP $CAPNG --silent && make --silent
  - sudo sh -c "NO_INTERACTION=1 make test"
