name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O2 -Wall -Werror"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        features:
          - "--with-cap --without-capng"
          - "--without-cap --with-capng"
    name: "Build and Test (PHP ${{ matrix.php }}, ${{ matrix.features }})"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3.5.0

      - name: Set up PHP
        uses: shivammathur/setup-php@2.25.2
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Install build dependencies
        run: sudo apt-get -qq update && sudo apt-get -qq install libcap-dev libcap-ng-dev

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Build
        run: phpize && ./configure ${{ matrix.features }} --silent && make --silent
        working-directory: chuid

      - name: Run tests
        run: sudo make test
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
        working-directory: chuid
